on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: build-project

jobs:
  build-project:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Create package cache
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-build-packages-${{ hashFiles('DESCRIPTION') }}
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Create drake cache
        uses: actions/cache@v1
        with:
          path: .drake
          key: ${{ runner.os }}-build-drake-${{ hashFiles('.drake/**/*') }}
      - name: Create OSF cache
        uses: actions/cache@v1
        with:
          path: osfcache
          key: ${{ runner.os }}-build-osf-${{ hashFiles('osfcache/**/*') }}
      - name: Run drake pipeline
        env:
          OSF_PAT: ${{ secrets.OSF_PAT }}
        run: Rscript make.R
