on:
  push:
    tags:
      - v*

name: export-data

jobs:
  export-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Create package cache
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-build-packages-${{ hashFiles('install.R', 'DESCRIPTION') }}
      - name: Install dependencies
        run: Rscript install.R
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
      - name: Create drake cache
        uses: actions/cache@v2
        with:
          path: .drake
          key: ${{ runner.os }}-build-drake-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-build-drake-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.R') }}
            ${{ runner.os }}-build-drake-${{ secrets.CACHE_VERSION }}-
            ${{ runner.os }}-build-drake-
      - name: Create OSF cache
        uses: actions/cache@v2
        with:
          path: "osfcache"
          key: ${{ runner.os }}-build-osf-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-build-osf-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.R') }}
            ${{ runner.os }}-build-osf-${{ secrets.CACHE_VERSION }}-
            ${{ runner.os }}-build-osf-
      - name: Run drake pipeline
        env:
          OSF_PAT: ${{ secrets.OSF_PAT }}
          F_OSF_UPLOAD: TRUE
          GH_TAG: ${{ steps.vars.outputs.tag }}
          F_RUN_TESTS: TRUE
        run: Rscript make.R
